# Generated by Django 4.2.11 on 2024-03-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback_form", "0002_rename_mail_feedback_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="phone",
            field=models.CharField(max_length=11),
        ),
    ]
